title: Follow
description: 오트론 8조 Follow
show_downloads: false

baseurl: "/" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://autron-follow.github.io" # change this to the base hostname & protocol for your site

cayman-blog:
   date_format: "%b %-d, %Y"

theme: # leave it empty

# social
   author: "sauber92"
   image: /thumbnail.png
